const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const puppeteer=require('puppeteer-core');
const {zipSync,strToU8}=require('fflate');
const origin=process.env.MENU_TEST_ORIGIN||'http://127.0.0.1:4173',fixture=process.env.MENU_FIXTURE_ORIGIN||origin,out=path.resolve(__dirname,'../artifacts/ui-audit');
assert.ok(['localhost','127.0.0.1'].includes(new URL(fixture).hostname),'Mutating browser checks require a local fixture');
fs.mkdirSync(out,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
  let checks=0;const pass=s=>{checks++;console.log('PASS '+s);};
  const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:process.env.CI?['--no-sandbox']:[]});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const state=async()=>await(await fetch(fixture+'/__dev/state')).json();
  const call=async(action,payload={},role='admin',endpoint='admin-api')=>{const r=await fetch(fixture+'/functions/v1/'+endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(endpoint==='admin-api'?{'x-admin-pin':'1','x-admin-role':role}:{'x-staff-pin':'1','x-staff-role':role})},body:JSON.stringify({action,...payload})});return {status:r.status,data:await r.json()};};
  const login=async()=>{await page.goto(origin+'/admin',{waitUntil:'networkidle0'});await page.type('#pin','1');await page.click('#loginForm button');await page.waitForSelector('#app:not([hidden])');};
  try{
    await fetch(fixture+'/__dev/reset?empty',{method:'POST'});
    await page.goto(origin+'/',{waitUntil:'networkidle0'});assert.equal(await page.$eval('#mainContent',el=>getComputedStyle(el).display),'none');pass('without QR the menu is gated');
    const settings=(await call('settings')).data.settings;await call('save-settings',{settings:{...settings,public_menu_enabled:true,restaurant_name:'Суши Крейзи'}});
    await page.goto(origin+'/?view=menu',{waitUntil:'networkidle0'});await page.waitForFunction(()=>!document.getElementById('guestGate').hidden===false);await page.evaluate(()=>addCart(1));assert.equal(await page.evaluate(()=>Object.keys(cart).length),0);pass('public menu is read-only');
    const table=(await state()).restaurant_tables[0];await page.goto(origin+'/?table='+table.qr_token,{waitUntil:'networkidle0'});await page.waitForFunction(()=>tableOrdering.ready);assert.equal((await state()).table_sessions.length,0);pass('QR scan does not open a table session');
    const groups=[{id:'size',name:'Размер',min:1,max:1,options:[{id:'large',name:'Большой',price_delta:300,is_available:true},{id:'small',name:'Маленький',price_delta:0,is_available:true}]}];await call('save-modifiers',{dishId:1,groups});
    await page.reload({waitUntil:'networkidle0'});await page.waitForFunction(()=>menuReady&&tableOrdering.ready);await page.evaluate(()=>addCart(1));await page.waitForSelector('#dishOptions[open]');await page.click('#dishOptions input[value=large]');await page.click('#dishOptions [type=submit]');
    const selected=await page.evaluate(()=>buildOrderPayload());assert.equal(selected.items[0].modifiers[0].optionId,'large');assert.equal(selected.items[0].unitPrice,(await state()).dishes[0].price+300);assert.deepEqual(await page.evaluate(()=>({qty:shownQty(1),total:shownTotal(getItem(1))})),{qty:1,total:selected.items[0].unitPrice});pass('guest selects a modifier and sees its price and card quantity');
    const data={action:'place-order',tableToken:table.qr_token,guestToken:crypto.randomUUID(),clientRequestId:crypto.randomUUID(),items:selected.items,paymentMethod:'cash'};
    const guestCall=async body=>{const r=await fetch(fixture+'/functions/v1/table-api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});assert.ok(r.ok,'guest API '+r.status);return r.json();};
    const placed=await guestCall(data),duplicate=await guestCall(data);assert.equal(placed.orderId,duplicate.orderId);
    const other=await guestCall({action:'bootstrap',tableToken:table.qr_token,guestToken:crypto.randomUUID()});assert.equal(other.orders.length,1);assert.equal(other.orders[0].isMine,false);assert.equal('guest_token' in other.orders[0],false);pass('table-wide orders and retry without exposing guest identity');
    assert.equal((await call('confirm-payment',{orderId:placed.orderId,paymentMethod:'cash'},'kitchen','staff-orders')).status,403);pass('kitchen cannot confirm payments');
    await login();await page.click('button[aria-label="Настройки ресторана"]');await page.waitForSelector('#restaurantSettings[open]');
    for(const width of [1440,390]){await page.setViewport({width,height:width===390?844:1000});await sleep(100);assert.ok(await page.$eval('#restaurantSettings',el=>el.scrollWidth<=el.clientWidth+2));await page.screenshot({path:path.join(out,'product-settings-'+width+'.png')});}pass('restaurant settings fit desktop and phone');
    await page.click('#settingsCancel');await page.setViewport({width:1440,height:1000});await page.click('#adminNav [data-section=menu]');await page.waitForSelector('[data-menu-action=edit]');await page.click('[data-menu-action=edit][data-id="1"]');await page.click('#dishForm details summary');assert.equal(await page.$$eval('#modifierEditor [data-option]',els=>els.length),2);pass('admin edits dish options');
    const photo=path.join(out,'qa-photo.png');fs.writeFileSync(photo,Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aPFkAAAAASUVORK5CYII=','base64'));const chooser=page.waitForFileChooser();await page.click('#dishImage + .product-button');await(await chooser).accept([photo]);await page.waitForFunction(()=>document.getElementById('dishImage').value.includes('/storage/v1/object/public/'));await page.waitForFunction(()=>document.getElementById('dishPreviewImage').complete&&document.getElementById('dishPreviewImage').naturalWidth>0);pass('photo upload, validation, storage URL and rendered preview');await page.evaluate(()=>closeDishEditor());
    const workbook=zipSync({
      '[Content_Types].xml':strToU8('<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'),
      '_rels/.rels':strToU8('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'),
      'xl/workbook.xml':strToU8('<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Menu" sheetId="1" r:id="rId1"/></sheets></workbook>'),
      'xl/_rels/workbook.xml.rels':strToU8('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'),
      'xl/worksheets/sheet1.xml':strToU8('<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>Название</t></is></c><c r="B1" t="inlineStr"><is><t>Категория</t></is></c><c r="C1" t="inlineStr"><is><t>Цена</t></is></c></row><row r="2"><c r="A2" t="inlineStr"><is><t>QA импорт</t></is></c><c r="B2" t="inlineStr"><is><t>QA категория</t></is></c><c r="C2"><v>1800</v></c></row></sheetData></worksheet>')});
    const file=path.join(out,'qa-menu.xlsx');fs.writeFileSync(file,workbook);await page.click('.menu-admin-toolbar .product-button');await page.waitForSelector('#menuImport[open]');await(await page.$('#menuWorkbook')).uploadFile(file);await page.waitForFunction(()=>!document.getElementById('confirmImport').disabled);assert.ok(await page.$eval('#importPreview',el=>el.textContent.includes('QA импорт')));await page.click('#confirmImport');await page.waitForSelector('#menuImport:not([open])');assert.ok((await state()).dishes.some(d=>d.name==='QA импорт'));pass('real XLSX parse, preview and additive import');
    await page.click('#adminNav [data-section=reports]');await page.waitForSelector('#paidReports .product-metrics');assert.ok(await page.$eval('#paidReports',el=>el.textContent.includes('Не оплачено')));assert.equal(await page.$('#shiftButton'),null);pass('paid and unpaid reports are distinct and shifts are automatic');
    await call('report-incident',{source:'qa',message:'QA connection failure'});await page.click('button[aria-label^="Уведомления"]');await page.waitForSelector('#incidentInbox[open]');assert.ok(await page.$eval('#incidentInbox',el=>el.textContent.includes('QA connection failure')));await page.click('[data-resolve]');pass('administrator incident inbox and resolution');
    await page.goto(origin+'/staff',{waitUntil:'networkidle0'});await page.type('#pin','1');await page.click('#loginForm button');await page.waitForSelector('#app:not([hidden])');
    await page.click('.floor-order-details summary');await page.click('button[onclick="openWaiterCancel('+placed.orderId+')"]');await page.waitForSelector('#waiterCancelDialog[open]');await page.click('#confirmWaiterCancel');await page.waitForSelector('#waiterCancelDialog:not([open])');assert.equal((await state()).orders.find(o=>o.id===placed.orderId).status,'cancelled');pass('waiter confirms cancellation before cooking');
    assert.deepEqual(errors,[]);console.log('Completed '+checks+' product browser checks.');
  }catch(e){await page.screenshot({path:path.join(out,'product-failure.png')});console.error(e);process.exitCode=1;}finally{await browser.close();await fetch(fixture+'/__dev/reset',{method:'POST'});}
})();
