-- Wolt JamBull snapshot 2026-10-08. Delivery surcharges; not dine-in prices.
-- Source options recovered from ../wolt-query.json category-listing.options.
-- Milk is a mutually exclusive choice. Pasta/hot dishes use existing guest option UI.
-- No writes to public restaurant data. Run against the existing demo schema only.
begin;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"bread","name":"Выбор хлеба","min":1,"max":1,"options":[{"id":"bread_0","name":"Ржаной","price_delta":0,"is_available":true},{"id":"bread_1","name":"Белый","price_delta":0,"is_available":true},{"id":"bread_2","name":"Домашний","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=2;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"milk","name":"На кокосовом молоке","min":0,"max":1,"options":[{"id":"milk_0","name":"Да","price_delta":595,"is_available":true},{"id":"milk_1","name":"Нет","price_delta":0,"is_available":true}]},{"id":"porridge","name":"Какая?","min":1,"max":1,"options":[{"id":"porridge_0","name":"Рисовая","price_delta":0,"is_available":true},{"id":"porridge_1","name":"Геркулесовая","price_delta":0,"is_available":true},{"id":"porridge_2","name":"Киноа","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=3;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"milk","name":"На кокосовом молоке","min":0,"max":1,"options":[{"id":"milk_0","name":"Да","price_delta":595,"is_available":true},{"id":"milk_1","name":"Нет","price_delta":0,"is_available":true}]},{"id":"porridge","name":"Какая?","min":1,"max":1,"options":[{"id":"porridge_0","name":"Рисовая","price_delta":0,"is_available":true},{"id":"porridge_1","name":"Геркулесовая","price_delta":0,"is_available":true},{"id":"porridge_2","name":"Киноа","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=4;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"topping","name":"топпинг","min":1,"max":1,"options":[{"id":"topping_0","name":"копченая индейка","price_delta":0,"is_available":true},{"id":"topping_1","name":"копченая телятина","price_delta":0,"is_available":true},{"id":"topping_2","name":"лосось малосольный","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=8;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"grain","name":"Рис или Киноа?","min":1,"max":1,"options":[{"id":"grain_0","name":"Рис","price_delta":0,"is_available":true},{"id":"grain_1","name":"Киноа","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=15;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"grain","name":"Рис или Киноа?","min":1,"max":1,"options":[{"id":"grain_0","name":"Рис","price_delta":0,"is_available":true},{"id":"grain_1","name":"Киноа","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=16;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"grain","name":"Рис или Киноа?","min":1,"max":1,"options":[{"id":"grain_0","name":"Рис","price_delta":0,"is_available":true},{"id":"grain_1","name":"Киноа","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=17;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"grain","name":"Рис или Киноа?","min":1,"max":1,"options":[{"id":"grain_0","name":"Рис","price_delta":0,"is_available":true},{"id":"grain_1","name":"Киноа","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=18;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"grain","name":"Рис или Киноа?","min":1,"max":1,"options":[{"id":"grain_0","name":"Рис","price_delta":0,"is_available":true},{"id":"grain_1","name":"Киноа","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=72;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"pasta","name":"Выберите пасту","min":1,"max":1,"options":[{"id":"pasta_0","name":"Тальятелле","price_delta":0,"is_available":true},{"id":"pasta_1","name":"Спагетти","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=60;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"pasta","name":"Выберите пасту","min":1,"max":1,"options":[{"id":"pasta_0","name":"Тальятелле","price_delta":0,"is_available":true},{"id":"pasta_1","name":"Спагетти","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=61;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"pasta","name":"Выберите пасту","min":1,"max":1,"options":[{"id":"pasta_0","name":"Тальятелле","price_delta":0,"is_available":true},{"id":"pasta_1","name":"Спагетти","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=62;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"pasta","name":"Выберите пасту","min":1,"max":1,"options":[{"id":"pasta_0","name":"Тальятелле","price_delta":0,"is_available":true},{"id":"pasta_1","name":"Спагетти","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=63;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"pasta","name":"Выберите пасту","min":1,"max":1,"options":[{"id":"pasta_0","name":"Тальятелле","price_delta":0,"is_available":true},{"id":"pasta_1","name":"Спагетти","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=64;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"side","name":"Гарнир","min":1,"max":1,"options":[{"id":"side_0","name":"Овощи гриль","price_delta":1355,"is_available":true},{"id":"side_1","name":"Картофель фри","price_delta":1255,"is_available":true},{"id":"side_2","name":"Картофельные дольки","price_delta":1255,"is_available":true},{"id":"side_3","name":"Рис","price_delta":955,"is_available":true},{"id":"side_4","name":"Брокколи","price_delta":1355,"is_available":true},{"id":"side_5","name":"Микс салата","price_delta":1055,"is_available":true},{"id":"side_6","name":"Киноа","price_delta":955,"is_available":true},{"id":"side_7","name":"Пюре","price_delta":955,"is_available":true},{"id":"side_8","name":"Без гарнира","price_delta":0,"is_available":true}]},{"id":"sauce","name":"Соус","min":0,"max":1,"options":[{"id":"sauce_0","name":"тар тар","price_delta":655,"is_available":true},{"id":"sauce_1","name":"кетчуп","price_delta":655,"is_available":true},{"id":"sauce_2","name":"горчица","price_delta":655,"is_available":true},{"id":"sauce_3","name":"терияки","price_delta":655,"is_available":true},{"id":"sauce_4","name":"пеппер сливочный","price_delta":655,"is_available":true},{"id":"sauce_5","name":"грибной сливочный","price_delta":655,"is_available":true},{"id":"sauce_6","name":"сладкий чили","price_delta":655,"is_available":true},{"id":"sauce_7","name":"хумус","price_delta":655,"is_available":true}]}]'::jsonb,updated_at=now() where id=81;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"side","name":"Гарнир","min":1,"max":1,"options":[{"id":"side_0","name":"Овощи гриль","price_delta":1355,"is_available":true},{"id":"side_1","name":"Картофель фри","price_delta":1255,"is_available":true},{"id":"side_2","name":"Картофельные дольки","price_delta":1255,"is_available":true},{"id":"side_3","name":"Рис","price_delta":955,"is_available":true},{"id":"side_4","name":"Брокколи","price_delta":1355,"is_available":true},{"id":"side_5","name":"Микс салата","price_delta":1055,"is_available":true},{"id":"side_6","name":"Киноа","price_delta":955,"is_available":true},{"id":"side_7","name":"Пюре","price_delta":955,"is_available":true},{"id":"side_8","name":"Без гарнира","price_delta":0,"is_available":true}]},{"id":"sauce","name":"Соус","min":0,"max":1,"options":[{"id":"sauce_0","name":"тар тар","price_delta":655,"is_available":true},{"id":"sauce_1","name":"кетчуп","price_delta":655,"is_available":true},{"id":"sauce_2","name":"горчица","price_delta":655,"is_available":true},{"id":"sauce_3","name":"терияки","price_delta":655,"is_available":true},{"id":"sauce_4","name":"пеппер сливочный","price_delta":655,"is_available":true},{"id":"sauce_5","name":"грибной сливочный","price_delta":655,"is_available":true},{"id":"sauce_6","name":"сладкий чили","price_delta":655,"is_available":true},{"id":"sauce_7","name":"хумус","price_delta":655,"is_available":true}]}]'::jsonb,updated_at=now() where id=82;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"side","name":"Гарнир","min":1,"max":1,"options":[{"id":"side_0","name":"Овощи гриль","price_delta":1355,"is_available":true},{"id":"side_1","name":"Картофель фри","price_delta":1255,"is_available":true},{"id":"side_2","name":"Картофельные дольки","price_delta":1255,"is_available":true},{"id":"side_3","name":"Рис","price_delta":955,"is_available":true},{"id":"side_4","name":"Брокколи","price_delta":1355,"is_available":true},{"id":"side_5","name":"Микс салата","price_delta":1055,"is_available":true},{"id":"side_6","name":"Киноа","price_delta":955,"is_available":true},{"id":"side_7","name":"Пюре","price_delta":955,"is_available":true},{"id":"side_8","name":"Без гарнира","price_delta":0,"is_available":true}]},{"id":"sauce","name":"Соус","min":0,"max":1,"options":[{"id":"sauce_0","name":"тар тар","price_delta":655,"is_available":true},{"id":"sauce_1","name":"кетчуп","price_delta":655,"is_available":true},{"id":"sauce_2","name":"горчица","price_delta":655,"is_available":true},{"id":"sauce_3","name":"терияки","price_delta":655,"is_available":true},{"id":"sauce_4","name":"пеппер сливочный","price_delta":655,"is_available":true},{"id":"sauce_5","name":"грибной сливочный","price_delta":655,"is_available":true},{"id":"sauce_6","name":"сладкий чили","price_delta":655,"is_available":true},{"id":"sauce_7","name":"хумус","price_delta":655,"is_available":true}]}]'::jsonb,updated_at=now() where id=83;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"side","name":"Гарнир","min":1,"max":1,"options":[{"id":"side_0","name":"Овощи гриль","price_delta":1355,"is_available":true},{"id":"side_1","name":"Картофель фри","price_delta":1255,"is_available":true},{"id":"side_2","name":"Картофельные дольки","price_delta":1255,"is_available":true},{"id":"side_3","name":"Рис","price_delta":955,"is_available":true},{"id":"side_4","name":"Брокколи","price_delta":1355,"is_available":true},{"id":"side_5","name":"Микс салата","price_delta":1055,"is_available":true},{"id":"side_6","name":"Киноа","price_delta":955,"is_available":true},{"id":"side_7","name":"Пюре","price_delta":955,"is_available":true},{"id":"side_8","name":"Без гарнира","price_delta":0,"is_available":true}]},{"id":"sauce","name":"Соус","min":0,"max":1,"options":[{"id":"sauce_0","name":"тар тар","price_delta":655,"is_available":true},{"id":"sauce_1","name":"кетчуп","price_delta":655,"is_available":true},{"id":"sauce_2","name":"горчица","price_delta":655,"is_available":true},{"id":"sauce_3","name":"терияки","price_delta":655,"is_available":true},{"id":"sauce_4","name":"пеппер сливочный","price_delta":655,"is_available":true},{"id":"sauce_5","name":"грибной сливочный","price_delta":655,"is_available":true},{"id":"sauce_6","name":"сладкий чили","price_delta":655,"is_available":true},{"id":"sauce_7","name":"хумус","price_delta":655,"is_available":true}]}]'::jsonb,updated_at=now() where id=84;
update alien_jambull_demo.dishes set modifier_groups='[{"id":"juice","name":"Выберите вкус сока","min":1,"max":1,"options":[{"id":"juice_0","name":"Апельсиновый","price_delta":0,"is_available":true}]}]'::jsonb,updated_at=now() where id=153;
commit;