-- Task 11: role-based access for owner/admin/waiter/kitchen.
-- PIN hashes are never exposed to browser clients. Edge Functions use the service role.
create table if not exists public.staff_members (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 80),
  role text not null check (role in ('owner','admin','waiter','kitchen')),
  pin_hash text not null check (char_length(pin_hash) = 64),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (role, pin_hash)
);

alter table public.staff_members enable row level security;

comment on table public.staff_members is
  'Restaurant staff identities and role-scoped PIN hashes. Access is only through protected Edge Functions.';

-- Temporary development bootstrap requested by the owner: PIN 1 for every role.
-- Replace these hashes with unique PINs before production handoff.
insert into public.staff_members (name, role, pin_hash)
values
  ('Владелец', 'owner',   '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b'),
  ('Администратор', 'admin', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b'),
  ('Официант', 'waiter',  '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b'),
  ('Кухня', 'kitchen',    '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b')
on conflict (role, pin_hash) do nothing;

create index if not exists staff_members_role_active_idx
  on public.staff_members (role, is_active);
