-- QR table ordering schema.
-- Staff PIN material is intentionally provisioned outside Git and is not stored here.

create table if not exists public.table_sessions (
  id uuid primary key default gen_random_uuid(),
  table_id uuid not null references public.restaurant_tables(id) on delete restrict,
  status text not null default 'open' check (status in ('open','closed')),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  updated_at timestamptz not null default now()
);

create unique index if not exists table_sessions_one_open_per_table
  on public.table_sessions(table_id) where status = 'open';

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  table_session_id uuid not null references public.table_sessions(id) on delete restrict,
  guest_token uuid not null,
  status text not null default 'submitted'
    check (status in ('submitted','accepted','preparing','ready','served','cancelled')),
  payment_method text not null check (payment_method in ('card','cash','kaspi')),
  comment text,
  total integer not null default 0 check (total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_session_created_idx
  on public.orders(table_session_id, created_at desc);
create index if not exists orders_guest_created_idx
  on public.orders(guest_token, created_at desc);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  dish_id integer references public.dishes(id) on delete set null,
  name text not null,
  quantity integer not null check (quantity > 0),
  unit_price integer not null check (unit_price >= 0),
  line_total integer not null check (line_total >= 0),
  item_comment text
);

create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists order_items_dish_idx on public.order_items(dish_id);

create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  table_session_id uuid not null references public.table_sessions(id) on delete cascade,
  guest_token uuid not null,
  kind text not null check (kind in ('waiter','bill','cutlery')),
  status text not null default 'open' check (status in ('open','resolved','cancelled')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists service_requests_session_idx
  on public.service_requests(table_session_id, created_at desc);

create table if not exists public.staff_access (
  id smallint primary key default 1 check (id = 1),
  pin_hash text not null,
  updated_at timestamptz not null default now()
);

alter table public.restaurant_tables enable row level security;
alter table public.table_sessions enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.service_requests enable row level security;
alter table public.staff_access enable row level security;

revoke all on public.restaurant_tables from anon, authenticated;
revoke all on public.table_sessions from anon, authenticated;
revoke all on public.orders from anon, authenticated;
revoke all on public.order_items from anon, authenticated;
revoke all on public.service_requests from anon, authenticated;
revoke all on public.staff_access from anon, authenticated;

insert into public.restaurant_tables (table_number, label)
values ('1', 'Стол 1')
on conflict (table_number) do nothing;

update public.restaurant_tables
set qr_token = '1617390c-d431-49aa-aa42-f4bb6a982117'::uuid,
    updated_at = now()
where table_number = '1';


create table if not exists public.admin_access (
  id smallint primary key default 1 check (id = 1),
  pin_hash text not null,
  updated_at timestamptz not null default now()
);

alter table public.admin_access enable row level security;
revoke all on public.admin_access from anon, authenticated;


-- Defense in depth: operational/admin tables are server-only.
create policy "deny direct client access" on public.restaurant_tables for all to anon, authenticated using (false) with check (false);
create policy "deny direct client access" on public.table_sessions for all to anon, authenticated using (false) with check (false);
create policy "deny direct client access" on public.orders for all to anon, authenticated using (false) with check (false);
create policy "deny direct client access" on public.order_items for all to anon, authenticated using (false) with check (false);
create policy "deny direct client access" on public.service_requests for all to anon, authenticated using (false) with check (false);
create policy "deny direct client access" on public.staff_access for all to anon, authenticated using (false) with check (false);
create policy "deny direct client access" on public.admin_access for all to anon, authenticated using (false) with check (false);
