-- Task 12: durable order status history for preparation-time analytics.
create table if not exists public.order_status_events (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  from_status text,
  to_status text not null,
  created_at timestamptz not null default now()
);

alter table public.order_status_events enable row level security;

create index if not exists order_status_events_order_created_idx
  on public.order_status_events (order_id, created_at);

create or replace function public.capture_order_status_change()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if old.status is distinct from new.status then
    insert into public.order_status_events (order_id, from_status, to_status, created_at)
    values (new.id, old.status::text, new.status::text, coalesce(new.updated_at, now()));
  end if;
  return new;
end;
$$;

drop trigger if exists orders_capture_status_change on public.orders;
create trigger orders_capture_status_change
after update of status on public.orders
for each row
when (old.status is distinct from new.status)
execute function public.capture_order_status_change();


revoke execute on function public.capture_order_status_change() from public, anon, authenticated;
